name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m pytest -v tests

    - name: Build coverage file
        run: |
          pytest --cov=week1-devops tests/ | tee pytest-coverage.txt

    - name: Pytest Coverage Comment
      id: coverageComment
      uses: nehasaha/week1-devops@main
      with: 
        pytest-coverage-path: ./pytest-coverage.txt